baseURL = "https://feuerwehr.altenhammer.bayern/"
locale = "de-DE"
title = "Freiwillige Feuerwehr Altenhammer"
defaultContentLanguage = "de"
buildFuture = true

[params]
  aktiveMitglieder    = 32
  foerdermitglieder   = 45
  gegruendet          = 1926
  jubilaeum           = true
  facebookUrl         = "https://www.facebook.com/profile.php?id=100061266252902"
  instagramUrl        = "https://www.instagram.com/ffw_altenhammer"
  whatsappUrl         = "https://wa.me/"
  heyformKontakt      = ""
  heyformSpende       = ""
  easyAppointmentsUrl = "https://buchung.feuerwehr.altenhammer.bayern"

[build]
  writeStats = true
